### ISSUE TITLE
Kontrolle Aufgabe 03

### ISSUE THREAD

**Issue by MelvinBusch** [SinaHaas/EIA2#1]
1. Im Steckbrief die Links zu Repository und Userpage unbedingt mit `target="_blank"` versehen!
2. Skizze, Anwendungsfall-Diagramm und AD's bitte immer in eine Datei packen.
3. Schöne AD's 🎨.
4. Event-Listener zur besseren Übersicht immer möglichst weit oben im Code platzieren.
5. Code enthält sehr viel Weißraum, sieht nicht so schick aus.
6. Ansonsten alles in Ordnung 👍🏻

_15.04 | 11:55 (mb)_

**Comment by Plagiatus** [comment]
Konzept in eine Datei packen, sonst gibt es eine Ampelstufe! codingstyle besser beachten (eigenschaften/attribute in camel case; Eventlistener und globale Variablen Position).
